use serde::{Deserialize, Serialize};


/// High-entropy random string generated by the client at the start of an
/// authorization request and held secret until code exchange (RFC 7636 § 4.1).
///
/// Generate one via [`PkceCodeChallenge::new_random_sha256`] rather than
/// constructing this directly.
#[derive(Clone)]
pub struct PkceCodeVerifier(String);

impl PkceCodeVerifier {

    /// Generates a cryptographically random verifier from `len` random bytes,
    /// base64url-encoded (no padding).
    ///
    /// `len` must be 32–96 so the encoded verifier stays within the 43–128
    /// character window required by RFC 7636 § 4.1.
    pub fn new_random(len: usize) -> Self {
        use base64::{engine::general_purpose::URL_SAFE_NO_PAD, Engine as _};
        use rand::RngCore;

        assert!((32..=96).contains(&len), "PKCE verifier byte length must be 32–96");

        let mut bytes = vec![0u8; len];
        rand::thread_rng().fill_bytes(&mut bytes);
        Self(URL_SAFE_NO_PAD.encode(&bytes))
    }

    pub fn as_str(&self) -> &str {
        &self.0
    }
}


/// S256 or Plain PKCE challenge method (RFC 7636 § 4.2).
///
/// Prefer `S256` — `Plain` transmits the raw verifier and is only
/// permitted when the client cannot support hashing.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum PkceCodeChallengeMethod {
    #[serde(rename = "S256")]
    S256,
    #[serde(rename = "plain")]
    Plain,
}


impl PkceCodeChallengeMethod {

    /// Returns the `code_challenge_method` string as sent in the authorize URL.
    pub fn as_str(&self) -> &str {
        match self {
            Self::S256 => "S256",
            Self::Plain => "plain",
        }
    }
}


/// PKCE code challenge derived from a [`PkceCodeVerifier`] (RFC 7636 § 4.2).
///
/// Sent in the authorization URL; the paired verifier is sent at code exchange
/// so the provider can confirm both requests come from the same client.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct PkceCodeChallenge {
    code_challenge: String,
    code_challenge_method: PkceCodeChallengeMethod,
}


impl PkceCodeChallenge {

    /// Generates a random S256 challenge and its paired verifier using 32 random bytes.
    pub fn new_random_sha256() -> (Self, PkceCodeVerifier) {
        Self::new_random_sha256_len(32)
    }

    /// Generates a random S256 challenge and its paired verifier using `len` random bytes.
    ///
    /// `len` must be 32–96 (yields a 43–128 character verifier per RFC 7636 § 4.1).
    pub fn new_random_sha256_len(len: usize) -> (Self, PkceCodeVerifier) {
        let verifier = PkceCodeVerifier::new_random(len);
        let challenge = Self::from_verifier_s256(&verifier);
        (challenge, verifier)
    }

    /// Derives an S256 challenge: `BASE64URL(SHA256(verifier))`.
    pub fn from_verifier_s256(verifier: &PkceCodeVerifier) -> Self {
        use base64::{engine::general_purpose::URL_SAFE_NO_PAD, Engine as _};
        use sha2::{Digest, Sha256};

        let hash = Sha256::digest(verifier.as_str().as_bytes());
        Self {
            code_challenge: URL_SAFE_NO_PAD.encode(hash),
            code_challenge_method: PkceCodeChallengeMethod::S256,
        }
    }

    /// Derives a Plain challenge: the verifier is sent as-is.
    ///
    /// Only use when the client cannot perform SHA-256 — Plain offers no
    /// security benefit over not using PKCE at all.
    pub fn from_verifier_plain(verifier: &PkceCodeVerifier) -> Self {
        Self {
            code_challenge: verifier.as_str().to_string(),
            code_challenge_method: PkceCodeChallengeMethod::Plain,
        }
    }

    /// The `code_challenge` value to include in the authorization URL.
    pub fn challenge(&self) -> &str {
        &self.code_challenge
    }

    /// The `code_challenge_method` value to include in the authorization URL.
    pub fn method(&self) -> &PkceCodeChallengeMethod {
        &self.code_challenge_method
    }
}